version: '3.8'

services:
  app:
    build: .
    container_name: paygate-posportal-app
    environment:
      - PORT=5000
      - NODE_ENV=development
      - APP_URL=http://20.2.221.64
      - APP_NAME=Paygate-PosPortal
      - APP_VERSION=1.0.0
      - APP_LENGTH_API_KEY=32
      - APP_TIMEZONE=Asia/Jakarta
      - MERCHANT_CODE=T9403
      - MERCHANT_KEY=DEV-nOqEQ9h8bBUHRc4SvjH6OzGwHTPMsnOgK0JxzDq3
      - PRIVATE_KEY=6EkU8-kHGQE-ZDWas-DPZgd-8wTMb
      - SANDBOX=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db_pos_portal
      - DB_USERNAME=devopsadmin
      - DB_PASSWORD=devops1
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - paygate-network

  db:
    image: mysql:5.7
    container_name: paygate-posportal-db
    environment:
      MYSQL_ROOT_PASSWORD: devops1
      MYSQL_DATABASE: db_pos_portal
      MYSQL_USER: devopsadmin
      MYSQL_PASSWORD: devops1
    ports:
      - "3306:3306"
    networks:
      - paygate-network
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - db_data:/var/lib/mysql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus


  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"

networks:
  paygate-network:
    driver: bridge
volumes:
  db_data:
  grafana-data:

